// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto_msg.LidarScan.proto

#ifndef PROTOBUF_Proto_5fmsg_2eLidarScan_2eproto__INCLUDED
#define PROTOBUF_Proto_5fmsg_2eLidarScan_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Proto_msg {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Proto_5fmsg_2eLidarScan_2eproto();
void protobuf_AssignDesc_Proto_5fmsg_2eLidarScan_2eproto();
void protobuf_ShutdownFile_Proto_5fmsg_2eLidarScan_2eproto();

class LidarScan;

// ===================================================================

class LidarScan : public ::google::protobuf::Message {
 public:
  LidarScan();
  virtual ~LidarScan();

  LidarScan(const LidarScan& from);

  inline LidarScan& operator=(const LidarScan& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LidarScan& default_instance();

  void Swap(LidarScan* other);

  // implements Message ----------------------------------------------

  LidarScan* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LidarScan& from);
  void MergeFrom(const LidarScan& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double timestamp = 1;
  inline bool has_timestamp() const;
  inline void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  inline double timestamp() const;
  inline void set_timestamp(double value);

  // optional uint32 seq = 2;
  inline bool has_seq() const;
  inline void clear_seq();
  static const int kSeqFieldNumber = 2;
  inline ::google::protobuf::uint32 seq() const;
  inline void set_seq(::google::protobuf::uint32 value);

  // repeated bytes data = 3;
  inline int data_size() const;
  inline void clear_data();
  static const int kDataFieldNumber = 3;
  inline const ::std::string& data(int index) const;
  inline ::std::string* mutable_data(int index);
  inline void set_data(int index, const ::std::string& value);
  inline void set_data(int index, const char* value);
  inline void set_data(int index, const void* value, size_t size);
  inline ::std::string* add_data();
  inline void add_data(const ::std::string& value);
  inline void add_data(const char* value);
  inline void add_data(const void* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& data() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_data();

  // @@protoc_insertion_point(class_scope:Proto_msg.LidarScan)
 private:
  inline void set_has_timestamp();
  inline void clear_has_timestamp();
  inline void set_has_seq();
  inline void clear_has_seq();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double timestamp_;
  ::google::protobuf::RepeatedPtrField< ::std::string> data_;
  ::google::protobuf::uint32 seq_;
  friend void  protobuf_AddDesc_Proto_5fmsg_2eLidarScan_2eproto();
  friend void protobuf_AssignDesc_Proto_5fmsg_2eLidarScan_2eproto();
  friend void protobuf_ShutdownFile_Proto_5fmsg_2eLidarScan_2eproto();

  void InitAsDefaultInstance();
  static LidarScan* default_instance_;
};
// ===================================================================


// ===================================================================

// LidarScan

// optional double timestamp = 1;
inline bool LidarScan::has_timestamp() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LidarScan::set_has_timestamp() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LidarScan::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LidarScan::clear_timestamp() {
  timestamp_ = 0;
  clear_has_timestamp();
}
inline double LidarScan::timestamp() const {
  // @@protoc_insertion_point(field_get:Proto_msg.LidarScan.timestamp)
  return timestamp_;
}
inline void LidarScan::set_timestamp(double value) {
  set_has_timestamp();
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:Proto_msg.LidarScan.timestamp)
}

// optional uint32 seq = 2;
inline bool LidarScan::has_seq() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LidarScan::set_has_seq() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LidarScan::clear_has_seq() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LidarScan::clear_seq() {
  seq_ = 0u;
  clear_has_seq();
}
inline ::google::protobuf::uint32 LidarScan::seq() const {
  // @@protoc_insertion_point(field_get:Proto_msg.LidarScan.seq)
  return seq_;
}
inline void LidarScan::set_seq(::google::protobuf::uint32 value) {
  set_has_seq();
  seq_ = value;
  // @@protoc_insertion_point(field_set:Proto_msg.LidarScan.seq)
}

// repeated bytes data = 3;
inline int LidarScan::data_size() const {
  return data_.size();
}
inline void LidarScan::clear_data() {
  data_.Clear();
}
inline const ::std::string& LidarScan::data(int index) const {
  // @@protoc_insertion_point(field_get:Proto_msg.LidarScan.data)
  return data_.Get(index);
}
inline ::std::string* LidarScan::mutable_data(int index) {
  // @@protoc_insertion_point(field_mutable:Proto_msg.LidarScan.data)
  return data_.Mutable(index);
}
inline void LidarScan::set_data(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:Proto_msg.LidarScan.data)
  data_.Mutable(index)->assign(value);
}
inline void LidarScan::set_data(int index, const char* value) {
  data_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:Proto_msg.LidarScan.data)
}
inline void LidarScan::set_data(int index, const void* value, size_t size) {
  data_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Proto_msg.LidarScan.data)
}
inline ::std::string* LidarScan::add_data() {
  return data_.Add();
}
inline void LidarScan::add_data(const ::std::string& value) {
  data_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:Proto_msg.LidarScan.data)
}
inline void LidarScan::add_data(const char* value) {
  data_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:Proto_msg.LidarScan.data)
}
inline void LidarScan::add_data(const void* value, size_t size) {
  data_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:Proto_msg.LidarScan.data)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
LidarScan::data() const {
  // @@protoc_insertion_point(field_list:Proto_msg.LidarScan.data)
  return data_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
LidarScan::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:Proto_msg.LidarScan.data)
  return &data_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Proto_msg

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Proto_5fmsg_2eLidarScan_2eproto__INCLUDED
