// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto_msg.LidarPacket.proto

#ifndef PROTOBUF_Proto_5fmsg_2eLidarPacket_2eproto__INCLUDED
#define PROTOBUF_Proto_5fmsg_2eLidarPacket_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Proto_msg {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Proto_5fmsg_2eLidarPacket_2eproto();
void protobuf_AssignDesc_Proto_5fmsg_2eLidarPacket_2eproto();
void protobuf_ShutdownFile_Proto_5fmsg_2eLidarPacket_2eproto();

class LidarPacket;

// ===================================================================

class LidarPacket : public ::google::protobuf::Message {
 public:
  LidarPacket();
  virtual ~LidarPacket();

  LidarPacket(const LidarPacket& from);

  inline LidarPacket& operator=(const LidarPacket& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LidarPacket& default_instance();

  void Swap(LidarPacket* other);

  // implements Message ----------------------------------------------

  LidarPacket* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LidarPacket& from);
  void MergeFrom(const LidarPacket& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double timestamp = 1;
  inline bool has_timestamp() const;
  inline void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  inline double timestamp() const;
  inline void set_timestamp(double value);

  // optional bytes data = 2;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 2;
  inline const ::std::string& data() const;
  inline void set_data(const ::std::string& value);
  inline void set_data(const char* value);
  inline void set_data(const void* value, size_t size);
  inline ::std::string* mutable_data();
  inline ::std::string* release_data();
  inline void set_allocated_data(::std::string* data);

  // @@protoc_insertion_point(class_scope:Proto_msg.LidarPacket)
 private:
  inline void set_has_timestamp();
  inline void clear_has_timestamp();
  inline void set_has_data();
  inline void clear_has_data();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double timestamp_;
  ::std::string* data_;
  friend void  protobuf_AddDesc_Proto_5fmsg_2eLidarPacket_2eproto();
  friend void protobuf_AssignDesc_Proto_5fmsg_2eLidarPacket_2eproto();
  friend void protobuf_ShutdownFile_Proto_5fmsg_2eLidarPacket_2eproto();

  void InitAsDefaultInstance();
  static LidarPacket* default_instance_;
};
// ===================================================================


// ===================================================================

// LidarPacket

// optional double timestamp = 1;
inline bool LidarPacket::has_timestamp() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LidarPacket::set_has_timestamp() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LidarPacket::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LidarPacket::clear_timestamp() {
  timestamp_ = 0;
  clear_has_timestamp();
}
inline double LidarPacket::timestamp() const {
  // @@protoc_insertion_point(field_get:Proto_msg.LidarPacket.timestamp)
  return timestamp_;
}
inline void LidarPacket::set_timestamp(double value) {
  set_has_timestamp();
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:Proto_msg.LidarPacket.timestamp)
}

// optional bytes data = 2;
inline bool LidarPacket::has_data() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LidarPacket::set_has_data() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LidarPacket::clear_has_data() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LidarPacket::clear_data() {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_->clear();
  }
  clear_has_data();
}
inline const ::std::string& LidarPacket::data() const {
  // @@protoc_insertion_point(field_get:Proto_msg.LidarPacket.data)
  return *data_;
}
inline void LidarPacket::set_data(const ::std::string& value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(value);
  // @@protoc_insertion_point(field_set:Proto_msg.LidarPacket.data)
}
inline void LidarPacket::set_data(const char* value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(value);
  // @@protoc_insertion_point(field_set_char:Proto_msg.LidarPacket.data)
}
inline void LidarPacket::set_data(const void* value, size_t size) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Proto_msg.LidarPacket.data)
}
inline ::std::string* LidarPacket::mutable_data() {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:Proto_msg.LidarPacket.data)
  return data_;
}
inline ::std::string* LidarPacket::release_data() {
  clear_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = data_;
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void LidarPacket::set_allocated_data(::std::string* data) {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete data_;
  }
  if (data) {
    set_has_data();
    data_ = data;
  } else {
    clear_has_data();
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:Proto_msg.LidarPacket.data)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Proto_msg

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Proto_5fmsg_2eLidarPacket_2eproto__INCLUDED
