# config/two_lidars_config.yaml
multi_lidar_node:
  ros__parameters:
    # The base frame for the merged point cloud
    base_frame_id: "base_link"
    # Topic for the merged point cloud
    merged_topic_name: "/points_merged"
    # Enable/Disable 3D PCD publishing
    publish_3d_pcd: true
    # Publishing frequency in Hz
    publish_frequency: 10.0

    # Enable/Disable initial ICP calibration. Set to false to skip.
    enable_icp_calibration: false

    # ROI Filter parameters - ENABLED
    enable_roi_filter: false
    # This list of strings determines the number of filters. The content can be anything.
    roi_filters: ["height_filter", "exclude_robot_body"]

    # Voxel Grid Filter parameters - ENABLED
    enable_voxel_filter: true
    voxel_leaf_size: 0.005 # 5mm

    # FlatScan (LaserScan) parameters
    publish_flatscan: true
    flatscan_topic_name: "/flatscan"
    flatscan_min_height: 0.1
    flatscan_max_height: 1.0
    flatscan_angle_min: -3.14159
    flatscan_angle_max: 3.14159
    flatscan_angle_increment: 0.0087
    flatscan_range_min: 0.1
    flatscan_range_max: 30.0

    # This list of strings determines the number of lidars. The content can be anything.
    lidars: ["lidar_0", "lidar_1"]

    # Filter 0 configuration block
    roi_filters.0:
      name: "height_filter"
      type: "positive"
      min_x: -1000.0
      max_x: 1000.0
      min_y: -1000.0
      max_y: 1000.0
      min_z: 0.02
      max_z: 2.2

    # Lidar 0 configuration block
    lidars.0:
      name: "lidar_0"
      enabled: true
      driver:
        lidar_type: "RSAIRY"
        input_type: "online"
        msop_port: 6667
        difop_port: 7777
      pointcloud:
        frame_id: "lidar_0_link"
        publish_raw: true
        raw_topic: "/lidar_0/points_raw"
      tf:
        x: 0.687
        y: -0.357
        z: 0.709
        roll: 1.277
        pitch: -1.317
        yaw: -4.417

    # Lidar 1 configuration block
    lidars.1:
      name: "lidar_1"
      enabled: true
      driver:
        lidar_type: "RSAIRY"
        input_type: "online"
        msop_port: 6668
        difop_port: 7778
      pointcloud:
        frame_id: "lidar_1_link"
        publish_raw: true
        raw_topic: "/lidar_1/points_raw"
      tf:
        x: -0.300
        y: 0.360
        z: -0.000
        roll: -0.006
        pitch: 0.079
        yaw: -3.945

    # Filter 1 configuration block
    roi_filters.1:
      name: "exclude_robot_body"
      type: "negative"
      min_x: -0.4
      max_x: 0.7
      min_y: -0.35
      max_y: 0.35
      min_z: 0.0
      max_z: 1.0
